# Generated by Django 5.0.8 on 2024-10-21 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AllInOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('netbios', models.CharField(default='', max_length=100, verbose_name='NetBios')),
                ('ubicacion', models.CharField(choices=[('LC-01', 'LC-01'), ('LC-02', 'LC-02'), ('LC-04', 'LC-04'), ('LC-05', 'LC-05'), ('LC-06', 'LC-06'), ('LC-07', 'LC-07'), ('LC-08', 'LC-08'), ('LC-09', 'LC-09'), ('LC-10', 'LC-10'), ('205 B', '205 B'), ('301 C', '301 C'), ('302 C', '302 C'), ('303 C', '303 C'), ('311 C', '311 C'), ('403 C', '403 C'), ('Biblioteca', 'Biblioteca'), ('Sala de profesores', 'Sala de profesores'), ('Co Work', 'Co Work'), ('Fabrica 4310', 'Fabrica 4310')], default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllInOneAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('netbios', models.CharField(default='', max_length=100, verbose_name='NetBios')),
                ('ubicacion', models.CharField(choices=[('Biblioteca', 'Biblioteca'), ('Bodega', 'Bodega'), ('Capacitación', 'Capacitación'), ('CoWork', 'Cowork'), ('DACOM', 'DACOM'), ('DAE', 'DAE'), ('DAF', 'DAF'), ('DAC', 'DAC'), ('Dirección', 'Dirección'), ('Dirección Gastronomía', 'Dirección Gastronomía'), ('Direción Mecánica', 'Dirección Mecánica'), ('Logística', 'Logística'), ('Pañol Construcción (sala 107B)', 'Pañol Construcción (sala 107B)'), ('Pañol Electrónica', 'Pañol Electrónica'), ('Pañol Gastronomía', 'Pañol Gastronomía'), ('Pañol Mecánica', 'Pañol Mecánica'), ('Sala CCTV Guardias Dunas', 'Sala CCTV Guardias Dunas'), ('Sala Profesores', 'Sala Profesores'), ('SubDirector Académico', 'SubDirector Académico'), ('Tutoría', 'Tutoría')], default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Azotea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('estado_activo', models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Con Detalles', 'Con Detalles')], default='Seleccione', max_length=50, verbose_name='Estado Activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodegaADR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('netbios', models.CharField(default='', max_length=100, verbose_name='NetBios')),
                ('estado_activo', models.CharField(choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Con Detalles', 'Con Detalles')], default='Seleccione', max_length=100, verbose_name='Estado Activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiniPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('netbios', models.CharField(default='', max_length=100, verbose_name='NetBios')),
                ('ubicacion', models.CharField(choices=[('DACOM', 'DACOM'), ('DAE', 'DAE'), ('DAF', 'DAF'), ('Edf A Piso 1 Ascensor', 'Edf A Piso 1 Ascensor'), ('Edf A Piso 1 Biblioteca', 'Edf A Piso 1 Biblioteca'), ('Edf A Piso 1 Coordinación', 'Edf A Piso 1 Coordinación'), ('Edf A Piso 2 Ascensor', 'Edf A Piso 2 Ascensor'), ('Edf A Piso 2 Escalera', 'Edf A Piso 2 Escalera'), ('Edf A Piso 2 Tutoría', 'Edf A Piso 2 Tutoría'), ('Edf A Piso 3 Ascensor', 'Edf A Piso 3 Ascensor'), ('Edf A Piso 3 Nodo (derecho)', 'Edf A Piso 3 Nodo (derecho)'), ('Edf B Piso 1 Mecánica', 'Edf B Piso 1 Mecánica'), ('Edf C Piso 3 Sala clase', 'Edf C Piso 3 Sala clase'), ('Edf C Piso 4 Casino (fuera)', 'Edf C Piso 4 Casino (fuera)'), ('Edf C Piso 5 Sala clase', 'Edf C Piso 5 Sala clase'), ('Edf C Piso 6 Sala clase', 'Edf C Piso 6 Sala clase'), ('Totem (fuera de oficina ADR)', 'Totem (fuera de oficina ADR)')], default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('netbios', models.CharField(default='', max_length=100, verbose_name='NetBios')),
                ('asignado_a', models.CharField(max_length=150, verbose_name='Asignado a')),
                ('ubicacion', models.CharField(choices=[('ADR', 'ADR'), ('Biblioteca', 'Biblioteca'), ('Bodega', 'Bodega'), ('Bodega Principal', 'Bodega Principal'), ('Capacitación', 'Capacitación'), ('Coordinación Docente', 'Coordinación Docente'), ('DAC', 'DAC'), ('DACOM', 'DACOM'), ('DAE', 'DAE '), ('DAF', 'DAF'), ('Domicilio', 'Domicilio'), ('Fabríca 4310', 'Fabríca 4310'), ('Hall Guardias', 'Hall Guardias'), ('Oficína Gastronomía', 'Oficína Gastronomía'), ('Oficína Mecánica', 'Oficína Mecánica'), ('Oficína Minería', 'Oficína Minería'), ('Oficína RRHH', 'Oficína RRHH'), ('Tutoría', 'Tutoría')], default='Seleccione', max_length=150, verbose_name='Ubicación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ubicacion', models.CharField(choices=[('Edificio A Tirana', 'Edificio A Tirana'), ('Edificio B Mecánica', 'Edificio B Mecánica'), ('Edificio C Dunas', 'Edificio C Dunas')], default='Seleccione', max_length=100, verbose_name='Edificio')),
                ('sala', models.CharField(choices=[('LC-01', 'LC-01'), ('LC-02', 'LC-02'), ('LC-03', 'LC-03'), ('LC-04', 'LC-04'), ('LC-05', 'LC-05'), ('LC-06', 'LC-06'), ('LC-07', 'LC-07'), ('LC-08', 'LC-08'), ('LC-09', 'LC-09'), ('LC-10', 'LC-10'), ('201 A', '201 A'), ('202 A', '202 A'), ('203 A', '203 A'), ('204 A', '204 A'), ('205 A', '205 A'), ('206 A', '206 A'), ('207 A', '207 A'), ('208 A', '208 A'), ('301 A', '301 A'), ('302 A', '302 A'), ('303 A', '303 A'), ('304 A', '304 A'), ('305 A', '305 A'), ('306 A', '306 A'), ('103 B', '103 B'), ('105 B', '105 B'), ('112 B', '112 B'), ('203 B', '203 B'), ('205 B', '205 B'), ('206 B', '206 B'), ('301 C', '301 C'), ('302 C', '302 C'), ('303 C', '303 C'), ('304 C', '304 C'), ('305 C', '305 C'), ('306 C', '306 C'), ('307 C', '307 C'), ('308 C', '308 C'), ('309 C', '309 C'), ('310 C', '310 C'), ('311 C', '311 C'), ('312 C', '312 C'), ('313 C', '313 C'), ('314 C', '314 C'), ('315 C', '315 C'), ('316 C', '316 C'), ('317 C', '317 C'), ('318 C', '318 C'), ('319 C', '319 C'), ('320 C', '320 C'), ('401 C', '401 C'), ('403 C', '403 C'), ('501 C', '501 C'), ('502 C', '502 C'), ('503 C', '503 C'), ('504 C', '504 C'), ('505 C', '505 C'), ('506 C', '506 C'), ('508 C', '508 C'), ('509 C', '509 C'), ('510 C', '510 C'), ('511 C', '511 C'), ('512 C', '512 C'), ('513 C', '513 C'), ('514 C', '514 C'), ('516 C', '516 C'), ('517 C', '517 C'), ('601 C', '601 C'), ('602 C', '602 C'), ('603 C', '603 C'), ('604 C', '604 C'), ('605 C', '605 C'), ('606 C', '606 C'), ('607 C', '607 C'), ('608 C', '608 C'), ('609 C', '609 C'), ('610 C', '610 C'), ('611 C', '611 C'), ('612 C', '612 C'), ('613 C', '613 C'), ('614 C', '614 C'), ('615 C', '615 C'), ('DAE (Sala Reuniones)', 'DAE (Sala Reuniones)'), ('DAE (Zócalo)', 'DAE (Zócalo)'), ('Fábrica 4310', 'Fábrica 4310')], default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=100, verbose_name='Activo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BDO')),
                ('netbios', models.CharField(max_length=100, verbose_name='NetBios')),
                ('entregado_por', models.CharField(blank=True, default='---------------', max_length=200, null=True, verbose_name='Entregado por')),
                ('en_reporte', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=False, null=True, verbose_name='En Reporte')),
                ('fecha_recepcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('recibido_por', models.CharField(blank=True, default='---------------', max_length=200, null=True, verbose_name='Recibido por')),
                ('entregado', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=False, null=True, verbose_name='Entregado')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha entrega')),
                ('operador_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador_entrega', to=settings.AUTH_USER_MODEL, verbose_name='Operador que entrega')),
                ('reporte_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporte_created', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionado por')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteAccesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incluido', models.BooleanField(default=False)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adr.accesorios')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adr.reporte')),
            ],
            options={
                'unique_together': {('reporte', 'accesorio')},
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='accesorios',
            field=models.ManyToManyField(through='adr.ReporteAccesorios', to='adr.accesorios'),
        ),
    ]
