# Generated by Django 5.0.8 on 2024-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='bdo',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='BDO'),
        ),
    ]
