# Generated by Django 5.0.8 on 2024-10-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0002_alter_allinone_bdo_alter_allinoneadmins_bdo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
    ]
