# Generated by Django 5.0.8 on 2024-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0004_remove_proyectores_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='marca',
            field=models.CharField(choices=[('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='marca',
            field=models.CharField(choices=[('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='marca',
            field=models.CharField(choices=[('A0LFCL', 'A0LFCL'), ('Apple', 'Apple'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Dell', 'Dell')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Epson', 'Epson'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Panasonic', 'Panasonic'), ('Viewsonic', 'Viewsonic')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='marca',
            field=models.CharField(choices=[('Intel', 'Intel')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='marca',
            field=models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='marca',
            field=models.CharField(choices=[('Epson', 'Epson')], default='', max_length=100, verbose_name='Marca'),
        ),
    ]
