# Generated by Django 5.0.8 on 2024-11-07 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0006_alter_allinone_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorios',
            options={'ordering': ['nombre'], 'verbose_name': 'Accesorio', 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.AlterModelOptions(
            name='allinone',
            options={'ordering': ['ubicacion', '-fecha_creacion'], 'verbose_name': 'All In One', 'verbose_name_plural': 'All In Ones'},
        ),
        migrations.AlterModelOptions(
            name='allinoneadmins',
            options={'ordering': ['ubicacion', '-fecha_creacion'], 'verbose_name': 'All In One Administrativo', 'verbose_name_plural': 'All In Ones Administrativos'},
        ),
        migrations.AlterModelOptions(
            name='azotea',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Equipo en Azotea', 'verbose_name_plural': 'Equipos en Azotea'},
        ),
        migrations.AlterModelOptions(
            name='bodegaadr',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Equipo en Bodega ADR', 'verbose_name_plural': 'Equipos en Bodega ADR'},
        ),
        migrations.AlterModelOptions(
            name='minipc',
            options={'ordering': ['ubicacion', '-fecha_creacion'], 'verbose_name': 'Mini PC', 'verbose_name_plural': 'Mini PCs'},
        ),
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ['ubicacion', '-fecha_creacion'], 'verbose_name': 'Notebook', 'verbose_name_plural': 'Notebooks'},
        ),
        migrations.AlterModelOptions(
            name='proyectores',
            options={'ordering': ['ubicacion', '-fecha_creacion'], 'verbose_name': 'Proyector', 'verbose_name_plural': 'Proyectores'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_recepcion'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='reporteaccesorios',
            options={'verbose_name': 'Accesorio de reporte', 'verbose_name_plural': 'Accesorios de reporte'},
        ),
        migrations.AlterUniqueTogether(
            name='reporteaccesorios',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='ubicacion',
            field=models.CharField(choices=[('', 'Seleccione una sala'), ('LC-01', 'LC-01'), ('LC-02', 'LC-02'), ('LC-04', 'LC-04'), ('LC-05', 'LC-05'), ('LC-06', 'LC-06'), ('LC-07', 'LC-07'), ('LC-08', 'LC-08'), ('LC-09', 'LC-09'), ('LC-10', 'LC-10'), ('205 B', '205 B'), ('301 C', '301 C'), ('302 C', '302 C'), ('303 C', '303 C'), ('311 C', '311 C'), ('403 C', '403 C'), ('Biblioteca', 'Biblioteca'), ('Sala de profesores', 'Sala de profesores'), ('Co Work', 'Co Work'), ('Fabrica 4310', 'Fabrica 4310')], default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='ubicacion',
            field=models.CharField(choices=[('', 'Seleccione una ubicación'), ('Biblioteca', 'Biblioteca'), ('Bodega', 'Bodega'), ('Capacitación', 'Capacitación'), ('CoWork', 'Cowork'), ('DACOM', 'DACOM'), ('DAE', 'DAE'), ('DAF', 'DAF'), ('DAC', 'DAC'), ('Dirección', 'Dirección'), ('Dirección Gastronomía', 'Dirección Gastronomía'), ('Direción Mecánica', 'Dirección Mecánica'), ('Logística', 'Logística'), ('Pañol Construcción (sala 107B)', 'Pañol Construcción (sala 107B)'), ('Pañol Electrónica', 'Pañol Electrónica'), ('Pañol Gastronomía', 'Pañol Gastronomía'), ('Pañol Mecánica', 'Pañol Mecánica'), ('Sala CCTV Guardias Dunas', 'Sala CCTV Guardias Dunas'), ('Sala Profesores', 'Sala Profesores'), ('SubDirector Académico', 'SubDirector Académico'), ('Tutoría', 'Tutoría')], default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='estado_activo',
            field=models.CharField(choices=[('', 'Seleccione un estado'), ('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Con Detalles', 'Con Detalles')], default='Seleccione', max_length=50, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('A0LFCL', 'A0LFCL'), ('Apple', 'Apple'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Dell', 'Dell')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='estado_activo',
            field=models.CharField(choices=[('', 'Seleccione un estado'), ('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Con Detalles', 'Con Detalles')], default='Seleccione', max_length=100, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('Apple', 'Apple'), ('Epson', 'Epson'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Panasonic', 'Panasonic'), ('Viewsonic', 'Viewsonic')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('Intel', 'Intel')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='ubicacion',
            field=models.CharField(choices=[('', 'Seleccione una ubicación'), ('DACOM', 'DACOM'), ('DAE', 'DAE'), ('DAF', 'DAF'), ('Edf A Piso 1 Ascensor', 'Edf A Piso 1 Ascensor'), ('Edf A Piso 1 Biblioteca', 'Edf A Piso 1 Biblioteca'), ('Edf A Piso 1 Coordinación', 'Edf A Piso 1 Coordinación'), ('Edf A Piso 2 Ascensor', 'Edf A Piso 2 Ascensor'), ('Edf A Piso 2 Escalera', 'Edf A Piso 2 Escalera'), ('Edf A Piso 2 Tutoría', 'Edf A Piso 2 Tutoría'), ('Edf A Piso 3 Ascensor', 'Edf A Piso 3 Ascensor'), ('Edf A Piso 3 Nodo (derecho)', 'Edf A Piso 3 Nodo (derecho)'), ('Edf B Piso 1 Mecánica', 'Edf B Piso 1 Mecánica'), ('Edf C Piso 3 Sala clase', 'Edf C Piso 3 Sala clase'), ('Edf C Piso 4 Casino (fuera)', 'Edf C Piso 4 Casino (fuera)'), ('Edf C Piso 5 Sala clase', 'Edf C Piso 5 Sala clase'), ('Edf C Piso 6 Sala clase', 'Edf C Piso 6 Sala clase'), ('Totem (fuera de oficina ADR)', 'Totem (fuera de oficina ADR)')], default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ubicacion',
            field=models.CharField(choices=[('', 'Seleccione una ubicación'), ('ADR', 'ADR'), ('Biblioteca', 'Biblioteca'), ('Bodega', 'Bodega'), ('Bodega Principal', 'Bodega Principal'), ('Capacitación', 'Capacitación'), ('Coordinación Docente', 'Coordinación Docente'), ('DAC', 'DAC'), ('DACOM', 'DACOM'), ('DAE', 'DAE '), ('DAF', 'DAF'), ('Domicilio', 'Domicilio'), ('Fabríca 4310', 'Fabríca 4310'), ('Hall Guardias', 'Hall Guardias'), ('Oficína Gastronomía', 'Oficína Gastronomía'), ('Oficína Mecánica', 'Oficína Mecánica'), ('Oficína Minería', 'Oficína Minería'), ('Oficína RRHH', 'Oficína RRHH'), ('Tutoría', 'Tutoría')], default='Seleccione', max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='estado',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('Epson', 'Epson')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='ubicacion',
            field=models.CharField(choices=[('', 'Seleccione un edificio'), ('Edificio A Tirana', 'Edificio A Tirana'), ('Edificio B Mecánica', 'Edificio B Mecánica'), ('Edificio C Dunas', 'Edificio C Dunas')], default='Seleccione', max_length=100, verbose_name='Edificio'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='accesorios',
            field=models.ManyToManyField(through='adr.ReporteAccesorios', to='adr.accesorios', verbose_name='Accesorios'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, verbose_name='NetBios'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='operador_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operador_entrega', to=settings.AUTH_USER_MODEL, verbose_name='Operador que entrega'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='reporte_creado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reporte_created', to=settings.AUTH_USER_MODEL, verbose_name='Recepcionado por'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='unive',
            field=models.CharField(blank=True, max_length=100, verbose_name='UNIVE'),
        ),
        migrations.AlterField(
            model_name='reporteaccesorios',
            name='accesorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adr.accesorios'),
        ),
    ]
