# Generated by Django 5.0.8 on 2024-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0007_alter_accesorios_options_alter_allinone_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteaccesorios',
            name='accesorio',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='accesorios',
        ),
        migrations.RemoveField(
            model_name='reporteaccesorios',
            name='reporte',
        ),
        migrations.AddField(
            model_name='reporte',
            name='bolso',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Bolso'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='cargador',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Cargador'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='equipo',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=2, verbose_name='Equipo'),
        ),
        migrations.DeleteModel(
            name='Accesorios',
        ),
        migrations.DeleteModel(
            name='ReporteAccesorios',
        ),
    ]
