# Generated by Django 5.0.8 on 2024-11-19 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0010_alter_allinone_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eliminados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('netbios', models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios')),
                ('ubicacion', models.CharField(blank=True, max_length=150, verbose_name='Ubicación')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Eliminación')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Registro Eliminado',
                'verbose_name_plural': 'Registros Eliminados',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
