# Generated by Django 5.0.8 on 2024-12-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0011_eliminados_delete_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinone',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='allinoneadmins',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='azotea',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='bodegaadr',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='minipc',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
        migrations.AddField(
            model_name='proyectores',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación'),
        ),
    ]
