# Generated by Django 5.0.8 on 2024-12-06 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0012_allinone_fecha_modificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo Modificado')),
                ('objeto_id', models.IntegerField(verbose_name='ID del Objeto Modificado')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(verbose_name='Valor Nuevo')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Modificación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Modificó')),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
