# Generated by Django 5.0.8 on 2024-12-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0013_historialcambios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambios',
            name='objeto_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del Objeto Modificado'),
        ),
    ]
