# Generated by Django 5.0.8 on 2024-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0016_alter_bodegaadr_estado_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegaadr',
            name='estado_activo',
            field=models.CharField(choices=[('', 'Seleccione un estado'), ('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Con Detalles', 'Con Detalles')], default='Bueno', max_length=100, verbose_name='Estado Activo'),
        ),
    ]
