# Generated by Django 5.0.8 on 2025-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0020_alter_allinone_marca_alter_allinoneadmins_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='azotea',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
        migrations.AddField(
            model_name='proyectores',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='netbios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS'),
        ),
    ]
