# Generated by Django 5.0.2 on 2025-06-02 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0021_azotea_netbios_proyectores_netbios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('marca', models.CharField(choices=[('', 'Seleccione una marca'), ('Logitech', 'Logitech'), ('Sony', 'Sony'), ('JBL', 'JBL'), ('Bose', 'Bose'), ('Genius', 'Genius'), ('Otra', 'Otra')], default='', max_length=100, verbose_name='Marca')),
                ('tipo_audio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Audio')),
                ('ubicacion', models.CharField(choices=[('', 'Seleccione una ubicación'), ('ADR', 'ADR'), ('Auditorio', 'Auditorio'), ('Biblioteca', 'Biblioteca'), ('Bodega', 'Bodega'), ('DAE', 'DAE'), ('Laboratorio de Idiomas', 'Laboratorio de Idiomas'), ('Sala de Clases', 'Sala de Clases'), ('Sala de Conferencias', 'Sala de Conferencias'), ('Sala de Profesores', 'Sala de Profesores'), ('Otra', 'Otra')], default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrador por')),
            ],
            options={
                'verbose_name': 'Equipo de Audio',
                'verbose_name_plural': 'Equipos de Audio',
                'ordering': ['ubicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('marca', models.CharField(choices=[('', 'Seleccione una marca'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('Dell', 'Dell'), ('HP', 'HP'), ('ViewSonic', 'ViewSonic'), ('Otra', 'Otra')], default='', max_length=100, verbose_name='Marca')),
                ('ubicacion', models.CharField(choices=[('', 'Seleccione una ubicación'), ('ADR', 'ADR'), ('Biblioteca', 'Biblioteca'), ('Bodega', 'Bodega'), ('Coordinación Docente', 'Coordinación Docente'), ('DACOM', 'DACOM'), ('DAE', 'DAE'), ('DAF', 'DAF'), ('DAC', 'DAC'), ('Laboratorio LC-01', 'Laboratorio LC-01'), ('Laboratorio LC-02', 'Laboratorio LC-02'), ('Laboratorio LC-03', 'Laboratorio LC-03'), ('Laboratorio LC-04', 'Laboratorio LC-04'), ('Laboratorio LC-05', 'Laboratorio LC-05'), ('Laboratorio LC-06', 'Laboratorio LC-06'), ('Laboratorio LC-07', 'Laboratorio LC-07'), ('Laboratorio LC-08', 'Laboratorio LC-08'), ('Laboratorio LC-09', 'Laboratorio LC-09'), ('Laboratorio LC-10', 'Laboratorio LC-10'), ('Oficina', 'Oficina'), ('Sala de Profesores', 'Sala de Profesores'), ('Otra', 'Otra')], default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('pulgadas', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pulgadas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrador por')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
                'ordering': ['ubicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.CharField(max_length=150, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('n_serie', models.CharField(max_length=100, verbose_name='Número Serie')),
                ('unive', models.CharField(max_length=100, verbose_name='UNIVE')),
                ('bdo', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='BDO')),
                ('estado', models.CharField(choices=[('', 'Seleccione una opción'), ('Operativo', 'Operativo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=100, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('marca', models.CharField(choices=[('', 'Seleccione una marca'), ('Samsung', 'Samsung'), ('Apple', 'Apple (iPad)'), ('Lenovo', 'Lenovo'), ('Huawei', 'Huawei'), ('Xiaomi', 'Xiaomi'), ('Otra', 'Otra')], default='', max_length=100, verbose_name='Marca')),
                ('ubicacion', models.CharField(choices=[('', 'Seleccione una ubicación'), ('ADR', 'ADR'), ('Biblioteca', 'Biblioteca'), ('Bodega', 'Bodega'), ('DAE', 'DAE'), ('Préstamo a Docente', 'Préstamo a Docente'), ('Préstamo a Estudiante', 'Préstamo a Estudiante'), ('Sala de Clases (Uso específico)', 'Sala de Clases (Uso específico)'), ('Otra', 'Otra')], default='Seleccione', max_length=100, verbose_name='Ubicación')),
                ('almacenamiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Almacenamiento')),
                ('netbios', models.CharField(blank=True, max_length=100, null=True, verbose_name='NetBIOS')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Registrador por')),
            ],
            options={
                'verbose_name': 'Tablet',
                'verbose_name_plural': 'Tablets',
                'ordering': ['ubicacion', '-fecha_creacion'],
            },
        ),
    ]
