# Generated by Django 5.0.2 on 2025-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0022_audio_monitor_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Otra', 'Otra')], default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='marca',
            field=models.CharField(choices=[('', 'Seleccione una marca'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Otra', 'Otra')], default='', max_length=100, verbose_name='Marca'),
        ),
    ]
