# Generated by Django 5.0.2 on 2025-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0024_remove_audio_tipo_audio_remove_monitor_pulgadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
    ]
