# Generated by Django 5.0.2 on 2025-06-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0025_alter_audio_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
    ]
