# Generated by Django 4.2 on 2025-06-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0027_alter_allinone_unive_alter_allinoneadmins_unive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablet',
            name='almacenamiento',
        ),
        migrations.AlterField(
            model_name='audio',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
    ]
