# Generated by Django 5.0.2 on 2025-06-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0028_remove_tablet_almacenamiento_alter_audio_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodegaadr',
            name='estado_activo',
        ),
        migrations.AddField(
            model_name='bodegaadr',
            name='ubicacion',
            field=models.CharField(choices=[('', 'Seleccione un estado'), ('Bueno', 'Bueno'), ('Malo', 'Malo'), ('Con Detalles', 'Con Detalles')], default='Bueno', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=255, verbose_name='Ubicación'),
        ),
    ]
