# Generated by Django 5.0.2 on 2025-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0029_remove_bodegaadr_estado_activo_bodegaadr_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegaadr',
            name='ubicacion',
            field=models.CharField(default='', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
    ]
