# Generated by Django 5.0.2 on 2025-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0030_alter_bodegaadr_ubicacion_alter_monitor_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodegaadr',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
    ]
