# Generated by Django 5.0.2 on 2025-06-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0031_alter_bodegaadr_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azotea',
            name='estado_activo',
        ),
        migrations.AddField(
            model_name='azotea',
            name='ubicacion',
            field=models.CharField(default='', max_length=100, verbose_name='Ubicación'),
        ),
    ]
