# Generated by Django 4.2 on 2025-06-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0032_remove_azotea_estado_activo_azotea_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='estado',
            field=models.CharField(default='Activo', max_length=100, verbose_name='Estado'),
        ),
    ]
