# Generated by Django 4.2 on 2025-06-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0033_alter_allinone_estado_alter_allinoneadmins_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azotea',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ubicación'),
        ),
    ]
