# Generated by Django 4.2 on 2025-06-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0034_alter_azotea_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinone',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='allinone',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='allinoneadmins',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='azotea',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='bodegaadr',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='eliminados',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='NetBios'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='minipc',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=150, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='marca',
            field=models.CharField(default='', max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='proyectores',
            name='ubicacion',
            field=models.CharField(default='Seleccione', max_length=100, verbose_name='Edificio'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='bdo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=30, null=True, verbose_name='BDO'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
