# Generated by Django 5.0.8 on 2025-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0035_alter_allinone_bdo_alter_allinone_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios'),
        ),
    ]
