# Generated by Django 5.0.8 on 2025-07-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0036_audio_netbios'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='netbios',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='NetBios'),
        ),
    ]
