# Generated by Django 5.0.8 on 2025-07-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr', '0037_monitor_netbios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminados',
            name='activo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='eliminados',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='eliminados',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='eliminados',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='eliminados',
            name='n_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Serie'),
        ),
        migrations.AlterField(
            model_name='eliminados',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='eliminados',
            name='unive',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UNIVE'),
        ),
    ]
