name: DB Backup (mysqldump + email)

on:
  schedule:
    # Domingo 14:00 Chile (UTC-3) = 17:00 UTC
    - cron: "0 17 * * 0"
  workflow_dispatch: {} # ejecución manual desde Actions

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: ${{ github.workspace }}
      BACKUP_DIR: ${{ github.workspace }}/backups

      # Variables de entorno desde GitHub Secrets
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system deps (mysql-client)
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare backup dir
        run: mkdir -p "$BACKUP_DIR"

      - name: Run Django backup command
        run: python manage.py backup_db

      - name: Upload artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: mysql-backup
          path: ${{ env.BACKUP_DIR }}/*.sql*
          if-no-files-found: ignore
