name: DB Backup (mysqldump + email)

on:
  schedule:
    # Domingo 14:00 Chile (UTC-3) = 17:00 UTC
    - cron: "0 17 * * 0"
  workflow_dispatch: {} # ejecución manual desde Actions

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: ${{ github.workspace }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug email env
        run: |
          echo "FROM=$EMAIL_HOST_USER"
          echo "TO=$EMAIL_RECIPIENTS"
          echo "SMTP=$EMAIL_HOST:$EMAIL_PORT"

      - name: Run Django backup command
        run: python manage.py backup_db

      - name: Upload backup artifact
        uses: actions/upload-artifact@v3
        with:
          name: mysql-backup
          path: backups/

